### ISSUE TITLE
There is no qa_model in your project

### ISSUE THREAD

**Issue by Square-Group-Sky** [INK-USC/SalKG#2]
When I ran qa.sh, I checked out that that there was not 'qa_model' in your python project. I am confused. Maybe it's in another python file, but I really can't find it. I appreciate your response。

**Comment by cnut1648** [comment]
Hi @Square-Group-Sky, thanks for your interest. Indeed we forgot to commit that file. Please look at this new commit [a023db754e02fb9cd8b306ba47a6bf28c9c16bf0](https://github.com/INK-USC/SalKG/commit/a023db754e02fb9cd8b306ba47a6bf28c9c16bf0). If you have any further question, please feel free to reopen this issue. Thanks!
